# Generated by Django 3.1.1 on 2020-09-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_in_str',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_str', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Data_in',
            new_name='Data_in_addr',
        ),
    ]
