# Generated by Django 3.1.1 on 2020-09-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsite', '0002_auto_20200921_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_in_addr',
            name='path_of_article_key',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data_in_addr',
            name='path_of_article_list',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
