# Generated by Django 3.1.1 on 2020-09-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsite', '0003_auto_20200921_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_in_addr',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
