# Generated by Django 3.1.1 on 2020-09-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djsite', '0005_auto_20200927_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_in_addr',
            old_name='path_of_article_key',
            new_name='key',
        ),
    ]
